@extends('manager.layout')

@section('body-class')
"body-dimmed"
@stop

@section('title')
<title>Support &rsaquo; {{ config('app.name')}}</title>
@stop

@section('content')
<div class="ui container">
	<h2 class="text-center font-regular font-massive">Support Center</h2>
	<h3 class="font-big font-regular margin-bottom">FAQs</h3>
</div>

<div class="ui container">
	<div class="ui stackable grid">
		<div class="sixteen wide mobile eleven wide tablet eleven wide computer column">
			<div class="ui segment">

				
				<div class="ui fluid accordion">
					<div class="active title">
					    <i class="dropdown icon"></i>
					    <span class="font-size-medium font-medium" id="social-media-accounts">
					    	How can I integrate my social media accounts?
					    </span>
					</div>
	  				<div class="active content">
					    <p class="margin-bottom">
					    	From your store manager page, navigate to <strong>Settings</strong> <i class="fa fa-angle-right"></i> <strong>General</strong> and scroll down the bottom in the <strong>Social Media</strong> section.<br /> Make sure to put the username of your social media account. <br />
					    	(<em>Note: For Facebook field, the username must be a valid Facebook page.</em>)
					    </p>
						<br />
	  				</div>
	  			</div>
				
				<div class="ui fluid accordion">
					<div class="active title">
					    <i class="dropdown icon"></i>
					    <span class="font-size-medium font-medium" id="slug">
					    	What is a slug?
					    </span>
					</div>
	  				<div class="active content">
					    <p>
					    	A slug is a unique string automatically generated by our system to create unique URLs for your product and category page(s). They are the lowercase version of your category/product name, spaces are replaced with dash (-) sign and any other special characters are omitted.
					    </p>
						<br />
	  				</div>
	  			</div>
				
				<div class="ui fluid accordion">
					<div class="active title">
					    <i class="dropdown icon"></i>
					    <span class="font-size-medium font-medium" id="subdomain">
					    	My subdomain is invalid
					    </span>
					</div>
	  				<div class="active content">
					    <p>
					    	When choosing a subdomain for your store, make sure to follow these guidelines: <br />
					    	<ul class="no-margin-bottom">
					    		<li>Must not contain special characters</li>
					    		<li>Can contain stressed letters (except stressed à)</li>
					    		<li>Can contain numbers (0-9)</li>
					    		<li>Uppercase characters will be replaced with its lowercase form</li>
					    	</ul>
					    </p>
	  				</div>
				</div>
			</div>
		</div>

		<div class="sixteen wide mobile five wide tablet five wide computer column">
			<span class="font-medium">Need more help?</span>
			<p>
			You can reach us out through our chat window located at the bottom right of your screen and we will respond to your message as soon as possible.
			Or visit our <a href="{{ route('manager.contact') }}">contact page</a> for more info.
			</p>
		</div>
	</div>
</div>
@stop